// Build-time fetch of the Satoshi UI font from Fontshare (keyless), so the raw font bytes are NOT
// committed to this repo. Satoshi is an ITF/Fontshare "free-proprietary" face: free to self-host to
// render your own product, but its files must not be redistributed as downloadable files -- which a
// committed (eventually public) repo would do. Keeping the bytes out of git and materializing them
// at install/build time keeps us on the "use / self-host" side of that line. The deployed site
// serves the woff2 same-origin (also sidesteps our COEP `require-corp` isolation, which would block
// a cross-origin CDN font). Mirrors how plugins/fontavious/generate-catalogue.mjs already talks to
// Fontshare's CSS API.
//
// Wiring: runs on `postinstall` (so `pnpm install` -- local and on Vercel -- materializes the font
// before any build) and is also prepended to the `dev`/`build` scripts as a belt-and-suspenders for
// checkouts where the gitignored files got cleared without reinstalling. Idempotent: a prior
// SUCCESSFUL run is detected by the presence of the real woff2 files and skipped; a prior FAILED run
// (css written, no fonts) always retries.

import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const UA =
	'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';

const FONT_DIR = fileURLToPath(new URL('../src/lib/fonts/Satoshi', import.meta.url));
const FILES_DIR = `${FONT_DIR}/fonts`;
const CSS_PATH = `${FONT_DIR}/Satoshi.css`;

// Fontshare returns family 'Satoshi' with a discrete @font-face per (weight, style). Map each to the
// per-weight family name the app's @font-face/`fonts-stack('Satoshi-Light', …)` call sites already
// use, so nothing downstream changes. 400-italic is historically named 'Satoshi-Italic'.
const NAME = {
	'normal|300': 'Satoshi-Light',
	'italic|300': 'Satoshi-LightItalic',
	'normal|400': 'Satoshi-Regular',
	'italic|400': 'Satoshi-Italic',
	'normal|500': 'Satoshi-Medium',
	'italic|500': 'Satoshi-MediumItalic',
	'normal|700': 'Satoshi-Bold',
	'italic|700': 'Satoshi-BoldItalic',
	'normal|900': 'Satoshi-Black',
	'italic|900': 'Satoshi-BlackItalic'
};

// A successful prior run leaves the real font file for the most-used weight on disk.
if (existsSync(`${FILES_DIR}/Satoshi-Regular.woff2`)) process.exit(0);

async function main() {
	mkdirSync(FILES_DIR, { recursive: true });

	let cssBody;
	try {
		const res = await fetch('https://api.fontshare.com/v2/css?f%5B%5D=satoshi', {
			headers: { 'User-Agent': UA }
		});
		if (!res.ok) throw new Error(`HTTP ${res.status}`);
		cssBody = await res.text();
	} catch (err) {
		warnFallback(`could not reach Fontshare (${err.message})`);
		return;
	}

	// Parse @font-face blocks -> [{ name, weight, style, url }]. Same shape as generate-catalogue's
	// resolveFontshare: protocol-relative //cdn.fontshare.com/...woff2 -> https:.
	const faces = [];
	for (const block of cssBody.split('@font-face')) {
		const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
		const style = block.match(/font-style:\s*([a-z]+)/i)?.[1];
		const woff2 = block.match(/url\('(\/\/[^']+\.woff2)'\)/)?.[1];
		if (!weight || !style || !woff2) continue;
		const name = NAME[`${style}|${weight}`];
		if (!name) continue; // a weight the app never references
		faces.push({ name, weight, style, url: `https:${woff2}` });
	}

	if (faces.length === 0) {
		warnFallback('Fontshare returned no usable @font-face');
		return;
	}

	const written = [];
	for (const f of faces) {
		try {
			const res = await fetch(f.url, { headers: { 'User-Agent': UA } });
			if (!res.ok) throw new Error(`HTTP ${res.status}`);
			const buf = Buffer.from(await res.arrayBuffer());
			writeFileSync(`${FILES_DIR}/${f.name}.woff2`, buf);
			written.push(f);
		} catch (err) {
			console.warn(`[fetch-fonts] skipped ${f.name}: ${err.message}`);
		}
	}

	if (written.length === 0) {
		warnFallback('every woff2 download failed');
		return;
	}

	writeFileSync(CSS_PATH, buildCss(written));
	console.log(`[fetch-fonts] Satoshi: ${written.length} faces fetched from Fontshare.`);
}

function buildCss(faces) {
	const head =
		'/**\n * Generated by scripts/fetch-fonts.mjs -- do not edit or commit.\n' +
		' * Font Family: Satoshi (c) Indian Type Foundry, via Fontshare (https://www.fontshare.com/fonts/satoshi).\n' +
		' * Self-hosted at build time; bytes are gitignored. See the script header for the licensing rationale.\n */\n\n';
	const blocks = faces.map(
		(f) =>
			`@font-face {\n` +
			`\tfont-family: '${f.name}';\n` +
			`\tsrc: url('$lib/fonts/Satoshi/fonts/${f.name}.woff2') format('woff2');\n` +
			`\tfont-weight: ${f.weight};\n` +
			`\tfont-style: ${f.style};\n` +
			`\tfont-display: swap;\n` +
			`}`
	);
	return head + blocks.join('\n\n') + '\n';
}

// Write a comment-only stylesheet so the static `import '$lib/fonts/Satoshi/Satoshi.css'` still
// resolves (no missing-asset build error); the app's font stacks fall back to system-ui. Never fail
// the build over a font fetch -- Vercel/dev must still succeed offline or if Fontshare is down.
function warnFallback(reason) {
	writeFileSync(
		CSS_PATH,
		`/* Satoshi not fetched (${reason}). Falling back to system-ui. */\n`
	);
	console.warn(`[fetch-fonts] Satoshi unavailable: ${reason} -> using system-ui fallback.`);
}

await main();
